place = input("Enter a Place Name: ")
person = input("Enter person Name: ")
adjective = input("Enter a adjective: ")
noun = input("Enter a Noun: ")
past_tense = input("Enter a Verb: ")
noun1 = input("Enter a Noun: ")
adjective1 = input("Enter a adjective: ")

print("Today, I went to the " + place)
print("with" + " " + person + ". First, We")
print("to the" + " " + adjective + ", adjective, an" )
print("The" + " " + noun + " " + "was the adjective.")
print("Afterwards, we" + " " + past_tense + " " + "at the")
print("adjective" + " " + noun1 + " " + "noun.")
print("It was a" + " " + adjective1 + " " + "day.")
